# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88552181f299f444b1f2ea2421e84f0b0d0b982adecaed3cffa57a747467d7f87bd089b1bbbd39863fbb4750728d1ee40813841a29d9651461409d26937406d6

test:
  secret_key_base: 9213cf99b4dc72523e940e46de08da660b298e8c7163e1c07905eba8247dfefd2edfce6b290adfd7740e21536208c4ffcc8e3b14ede72e8b468702237fa8cd88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
